### ISSUE TITLE
Conflict between dlt and Delta Live Tables in Databricks Environment

### ISSUE THREAD

**Issue by rodrigoruhragency** [dlt-hub/dlt#1022]
### dlt version

dlt stable 0.4.4

### Describe the problem

Attempting to use the dlt (Data Load Tool) in Databricks leads to confusion as "dlt" is interpreted as "Delta Live Tables," an existing library. This prevents direct usage of dlt's functionalities.
This issue arises because in Databricks, upon cluster initialization, certain libraries, including Delta Live Tables (referred to as "dlt"), are pre-installed in a location that takes precedence over other imports in a Python script. As a result, when attempting to import the DLT (Data Load Tool) using the "import dlt" command, the interpreter prioritizes the pre-installed Delta Live Tables library instead of the intended Data Load Tool.

### Expected behavior

The expected behavior is that users can install and utilize the dlt directly by simply executing "import dlt" without requiring any additional configuration on Databricks clusters.

### Steps to reproduce

in a Dabricks python notebook:

`!pip install dlt[databricks]`

```
import dlt
from dlt.sources.helpers import requests
```

### Operating system

Other

### Runtime environment

Other

### Python version

3.11

**Comment by VioletM** [comment]
@rodrigoruhragency 
Here are the instructions that should help you to solve the issue, please, let me know if it helps!
# Steps
## 1. Add an init script
You need to add an init script (which runs on cluster startup) to install the dltHub dlt package, and modify the name of Databricks’ dlt package so that the dltHub dlt package can be used without any issues. 

Add an `init.sh`  file somewhere in your Workspace directory with the following content:
```
#! /bin/bash

# move Databricks' dlt package to a different folder name
mv /databricks/spark/python/dlt/ /databricks/spark/python/dlt_dbricks

# Replace all mentions of `dlt` with `dlt_dbricks` so that Databricks' dlt 
# can be used as `dlt_dbricks` in the notebook instead
find /databricks/spark/python/dlt_dbricks/ -type f -exec sed -i 's/from dlt/from dlt_dbricks/g' {} \;

# Install dltHub dlt
pip install git+https://github.com/dlt-hub/dlt.git@issue-502
```

## 2. Enable the init script in the cluster. 
Go back to your cluster settings, click “Edit” in the top right corner, scroll all the way down and unfurl the “Advanced Options” section. Then click on “Init scripts” and select the file you just created as follows:
![image](https://github.com/dlt-hub/dlt/assets/9139429/ed0f2737-94da-4e68-9a4f-f1a96ddda04d)
Clicking “Add” and then “Confirm” will trigger a restart. 

# Usage
Now every time you create a new Notebook on this cluster, you will be able to use the dltHub package as normal with the dlt  reference, and any of Databricks’ dlt functionality can be used with the `dlt_dbricks`  reference.

**Comment by VioletM** [comment]
@rodrigoruhragency please, let us know if the proposed solution solved your issue

**Comment by rodrigoruhragency** [comment]
Yes, fortunately I was able to use dlt in databicks now, thank you very much.
There is also another option: change the priority of the paths libraries:

`import sys
print(sys.path)

desired_path = '/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages'
sys.path.insert(0, desired_path)`

after running this, dlt can be installed and used freely without interfering with "delta live tables".

**Comment by VioletM** [comment]
Thanks!
This sounds even simpler 🔥

**Comment by VioletM** [comment]
To enable `dlt` on serverless compute, in your databricks notebook, execute the following code before running the notebook:

```
import sys

# there's no dlt in serverless but a patching module is still there, it is a first import hook
# which is disabled below
import os
metas = list(sys.meta_path)
sys.meta_path = metas[1:]
del os.environ["RUNTIME"]

import dlt
sys.meta_path = metas
```

**Comment by maarten-betman** [comment]
The path of `DeltaLiveTablesHook.py` and `DeltaLiveTablesHook.py` has changed. 
Only small change and could create a PR if ok👍🏻 

```bash
# Replace mentions of `dlt` with `dlt_dbricks` in DeltaLiveTablesHook.py to
# avoid import errors
sed -i "s/'dlt'/'dlt_dbricks'/g" /databricks/python_shell/lib/dbruntime/DeltaLiveTablesHook.py
sed -i "s/from dlt/from dlt_dbricks/g" /databricks/python_shell/lib/dbruntime/DeltaLiveTablesHook.py
```
