### ISSUE TITLE
Total_path in PageNumberPaginator does not work always

### ISSUE THREAD

**Issue by MiguelElGallo** [dlt-hub/dlt#1414]
### Feature description

The total_path PageNumberPaginator should expect the path only in the first page. Since some APIs provide that value in the first page, after that, is not available.

See this example, the first page:
```json
{
  "data": [
    {
      "datasetId": 74,
      "startTime": "2024-05-25T15:15:00.000Z",
      "endTime": "2024-05-25T15:30:00.000Z",
      "value": 7328.06
    }
  ],
  "pagination": {
    "total": 6,
    "lastPage": 6,
    "nextPage": 2,
    "prevPage": 0,
    "currentPage": 1,
    "perPage": 1,
    "from": 0,
    "to": 1
  }
}
```
Total path set to ```pagination.total```
But next page looks:
```json
{
  "data": [
    {
      "datasetId": 74,
      "startTime": "2024-05-25T15:00:00.000Z",
      "endTime": "2024-05-25T15:15:00.000Z",
      "value": 7377.55
    }
  ],
  "pagination": { "perPage": 1, "currentPage": 2, "from": 1, "to": 2 }
}
```

No more pagination.total in the second page, it fails with 
```log
ValueError: Total pages is not found in the response in PageNumberPaginator. Expected a response with a 'pagination.total' key, got {'data': [{'datasetId': 74, 'startTime': '2024-05-25T15:15:00.000Z', 'endTime': '2024-05-25T15:30:00.000Z', 'value': 7328.06}], 'pagination': {'currentPage': 2, 'perPage': 1, 'from': 1, 'to': 2}}
```

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Proposed solution

Add another parameter Total_path_only_on_first_page type boolean.
If set to True, should not expect the total_path in other pages than the first one.

**Comment by burnash** [comment]
Hi @MiguelElGallo 

Thanks for bringing this up and sorry for the delayed response! It seems like you've encountered a pretty specific edge case. I think this is a valid scenario that can occur with some APIs. However, instead of adjusting the core paginator to handle this particular case, a more flexible approach would be to implement a custom paginator.

You can create a custom paginator by deriving from PageNumberPaginator and overriding the state management of `total` across different pages, here's the relevant doc section: https://dlthub.com/docs/general-usage/http/rest-client#implementing-a-custom-paginator.

Let me know if it helps.

**Comment by MiguelElGallo** [comment]
@burnash Thanks for the info. That sounds like a sensible solution. I will give it a go!
