### ISSUE TITLE
LanceDB destination with Ollama embedding

### ISSUE THREAD

**Issue by zilto** [dlt-hub/dlt#1973]
### Documentation description

User contacted me with the following question:

> how can I swap openai embeddings for an ollama model nomic-embed-text. While [ollama isn't mentioned as supported in the docs](https://dlthub.com/docs/dlt-ecosystem/destinations/lancedb#configure-the-destination), the last bullet point suggests ollama could work.

As far as I know, the LanceDB destination leverages the [LanceDB registry and should support Ollama](https://lancedb.github.io/lancedb/embeddings/available_embedding_models/text_embedding_functions/ollama_embedding/).
 The docs could more explicitly mention Ollama support (or not) and show how to set it up. In particular, what's the config key to set the Ollama server URL.

### Are you a dlt user?

Yes, I'm already a dlt user.

**Comment by Analect** [comment]
@Pipboyguy .... Just adding some colour here pertaining to [this slack thread](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1729531856233769). I had been in touch with @zilto ... since it was pertaining to his [blog](https://blog.dagworks.io/p/from-blog-to-bot-build-a-rag-app).

I wanted to be able to swap-out his openai usage for calculating embeddings on a self-hosted ollama embeddings model and just have them calculated locally.

I tried with these settings.

```
# using  Ollama
os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL_PROVIDER"] = "ollama"
os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL"] = "nomic-embed-text"
```

This errored with:
```
PipelineStepFailed: Pipeline execution failed at stage sync with exception:

<class 'dlt.common.configuration.exceptions.ConfigValueCannotBeCoercedException'>
Configured value for field embedding_model_provider cannot be coerced into type typing.Literal['gemini-text', 'bedrock-text', 'cohere', 'gte-text', 'imagebind', 'instructor', 'open-clip', 'openai', 'sentence-transformers', 'huggingface', 'colbert']
```
Is that somehow due to `ollama` missing from this list: https://github.com/dlt-hub/dlt/blob/devel/dlt/destinations/impl/lancedb/configuration.py#L50-L62

Also, since I'm running my ollama at host `192.168.192.3:11434`, it would be great to be able to pass through an ollama host that doesn't just default to `localhost:11434`. 

Perhaps that needs handling for something like `os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL_PROVIDER_HOST"] = "<some-url>:11434"`

**Comment by akelad** [comment]
@Pipboyguy I saw you were having some more discussions on [slack](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1729695224415889?thread_ts=1729531856.233769&cid=C04DQA7JJN6) about this - did you already start working on this? We had assigned Rahul to look into it, but if you're already on it I'll unassign it.

**Comment by Pipboyguy** [comment]
Hi @akelad . I haven't started on this. Rahul can have a go!

**Comment by Pipboyguy** [comment]
@zilto @Analect Turns out that the ollama provider has been added in the devel branch, and I tested it so seems to be working just fine. Please try again with:

```shell
pip install "git+https://github.com/dlt-hub/dlt.git@devel[lancedb]" ollama
```

**Comment by zilto** [comment]
Hi @Pipboyguy! Sorry for the delay. I originally opened issue after chatting with @Analect, but I never used Ollama myself. I'm waiting on a new SSD this week. Once I receive it, I could try the Ollama support.

Looking at the PR, it seems like a small change (as we expected) and it doesn't seem to conflict with other features

**Comment by Pipboyguy** [comment]
> @Pipboyguy do you need a reviewer here?

Yes please :)

**Comment by Analect** [comment]
@Pipboyguy @zilto 
I can confirm this works. I was testing this against this [notebook](https://github.com/DAGWorks-Inc/burr/blob/main/examples/rag-lancedb-ingestion/notebook.ipynb) example. In the 4th code cell, I commented-out the `openai` embedding model references and replaced them with:

```
os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL_PROVIDER"] = "ollama"
os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL"] = "nomic-embed-text"
os.environ["DESTINATION__LANCEDB__EMBEDDING_MODEL_PROVIDER_HOST"] = "http://192.168.192.3:11434"
```

I have an ollama server running at that end-point.

To get this to work, I ended up installing `dlt` using:
`pip install "git+https://github.com/dlt-hub/dlt.git@1973-lancedb-destination-with-ollama-embedding"` (ie. the branch with fix in place).

Thanks for your help with this.
