### ISSUE TITLE
dlt will always try to truncate tables for resources for replace_strategy "truncate-and-insert" even if the table doesnt exist

### ISSUE THREAD

**Issue by jonaswvd** [dlt-hub/dlt#765]
### dlt version

0.3.21

### Describe the problem

If replace_strategy is "truncate-and-insert" then for resources with write_dispositon="replace" dlt will always try to truncate the table.
If a table has been deleted in the destination, then _dlt_version table and destination becomes out of sync, and the table will be tried deleted by dlt even though it doesn't exist.

For MSSQL destination this results in error:
"Cannot find the object "table_name" because it does not exist or you do not have permissions."

### Expected behavior

I would expect dlt not to try to delete tables if they do not exist.

### Steps to reproduce

* Use default replace_strategy or set explicit to "truncate-and-insert"
* Have a table in destination that a resource writes to with write_dispositon="replace".
* Do a successful pipeline run.
* Delete the table in the destination
* Pipeline can only run successfully again until if table is recreated manually in destination or by changing replace_strategy (deleting content from _dlt_version manually should also do the trick)

If I delete the .dlt folder in ~ dlt will get the schema from the destination in the _dlt_version table, through the following call stack:
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/pipeline/pipeline.py#L514
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/pipeline/pipeline.py#L1168
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/destinations/job_client_impl.py#L253

If I do not delete the .dlt folder, dlt will get the same schema stored in the .dlt (originally gotten from the destination as according to above):
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/common/storages/schema_storage.py#L30

Anyhow, we will end up here with f=job_client.should_truncate_table_before_load returning True:
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/destinations/job_client_impl.py#L144
and because the table exist in the schema even though it doesnt in the destination, the following line returns False:
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/load/load.py#L283

Resulting in a sql query trying to "TRUNCATE TABLE "schema_name"."table_name"; for nonexisting table here:
https://github.com/dlt-hub/dlt/blob/0843ff61af0fc475bb4dd380f6ec5b1b74059e36/dlt/destinations/mssql/sql_client.py#L123

### Operating system

Windows

### Runtime environment

Local

### Python version

3.11

### Other deployment details

destination is MSSQL

**Comment by rudolfix** [comment]
@jonaswvd  thanks for the report! this issue is actually deeper and to solve it properly, dlt would need to look for deleted tables before it starts extracting data. deleting a table should also reset the associated resource state and the schema to the initial one.
currently we only detect if the dataset was deleted and we reset all the schemas and state associated with it.

things you can do now:
right now we support such thing from cli: https://dlthub.com/docs/reference/command-line-interface#selectively-drop-tables-and-reset-state
and there's a helper class for programmatic use `DropCommand`

our take to solve your use case it to introduce a refresh modes which will drop tables for you automatically:
https://github.com/dlt-hub/dlt/issues/588

@jonaswvd I'll convert this bug report into feature request - to detect the deleted tables like we detect the deleted datasets. I'm not 100% sure we want to do that for every destination - we'd need to reflect the database schema before pipeline run. it is quite expensive

**Comment by jonaswvd** [comment]
Thank youi for the response!

Am I using the drop command wrong?
![image](https://github.com/dlt-hub/dlt/assets/50017053/44de6b8a-1249-48ff-935b-c1e03c74e00e)

**Comment by rudolfix** [comment]
@jonaswvd are you on our slack? ping me there. maybe there's something weird with MSSQL. we need to reproduce this error. typically when you see the output like you see the command is running right and you should not have any problems :/
