### ISSUE TITLE
Core extensions to support database replication

### ISSUE THREAD

**Issue by jorritsandbrink** [dlt-hub/dlt#947]
### Feature description

Extend the core to enable database replication. This needs to be done before #933. 

Context:

1. https://dlthub-community.slack.com/archives/C06EYJ2Q37C/p1707135498114549?thread_ts=1706550675.731069&cid=C06EYJ2Q37C
![image](https://github.com/dlt-hub/dlt/assets/47451109/f9a4968f-932b-412d-9e4e-66299acadc9e)

2. https://github.com/dlt-hub/dlt/issues/933#issuecomment-1931740029
![image](https://github.com/dlt-hub/dlt/assets/47451109/4e9de6e5-0af6-451a-bd57-e6922304677b)

### Are you a dlt user?

None

### Use case

Database replication, CDC, efficient incremental processing

### Related issues

#933

**Comment by jorritsandbrink** [comment]
@rudolfix It seems like typically the entire record is provided for update operations, even if only a subset of columns has been changed. I checked Postgres, MySQL, SQL Server, and Delta tables.

Do we need partial updates?

**Comment by rudolfix** [comment]
@jorritsandbrink does it make things easier? I assume in that case we could reuse existing merge job right? then we do need only a flag to delete records because existing code handles replace rows and inserts by checking the primary keys.

it would be cool to have partial updates but if that is 2x more work then let's do the above instead
