### ISSUE TITLE
DuckDB - append adds extra rows even when there's no updated data

### ISSUE THREAD

**Issue by karakanb** [dlt-hub/dlt#971]
### dlt version

0.4.4

### Describe the problem

The `append` disposition is supposed to not append if there's no new data and it works that way in postgres destination, but with duckdb it reinserts the data.

### Expected behavior

in the second iteration, the output should not have an extra row since there's no new data, however it appends anyway.

### Steps to reproduce

use the following code:

```python
import os
import dlt
from dlt.sources.credentials import ConnectionStringCredentials
from dlt.common import pendulum
import shutil

import duckdb
from ingestr.src.sql_database import sql_table


def load_standalone_table_resource() -> None:
    pipeline = dlt.pipeline(
        pipeline_name="output",
        destination=dlt.destinations.duckdb(
            credentials=uri,
        ),
        pipelines_dir="pipeline_dataappendprob",
        dataset_name="testschema_append",
    )

    # Run the resources together
    info = pipeline.run(
        sql_table(
            credentials=uri,
            schema="testschema_append",
            table="input",
            incremental=dlt.sources.incremental(
                "updated_at",
            ),
        ),
        dataset_name="testschema_append",
        table_name="output",
        write_disposition="append",
    )
    print(info)


def get_abs_path(relative_path):
    return os.path.abspath(os.path.join(os.path.dirname(__file__), relative_path))

abs_db_path = get_abs_path("sample_append.db")
uri = f"duckdb:///sample_append.db"
conn = duckdb.connect(abs_db_path)
def setup_db():
    try:
        shutil.rmtree(get_abs_path("pipeline_dataappendprob"))
    except:
        pass

    conn.execute("DROP SCHEMA IF EXISTS testschema_append CASCADE")
    conn.execute("CHECKPOINT")

    conn.execute("CREATE SCHEMA testschema_append")
    conn.execute("CREATE TABLE testschema_append.input (id INTEGER, val VARCHAR, updated_at DATE)")
    conn.execute("INSERT INTO testschema_append.input VALUES (1, 'val1', '2022-01-01'), (2, 'val2', '2022-01-02')")
    conn.execute("CHECKPOINT")


def run(iteration: int):
    print("running iteration", iteration)
    load_standalone_table_resource()

    print("--------------")
    print("source:")
    conn.sql("select * from testschema_append.input").show()
    print()
    print("destination:")
    conn.sql("select * from testschema_append.output").show()
    print("--------------")

setup_db()
run(1)
run(2)
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

dlt sql_table source

### Other deployment details

official duckdb

**Comment by rudolfix** [comment]
@karakanb thanks for bug report. we will investigate.

**Comment by IlyaFaer** [comment]
Can't reproduce it yet
@karakanb, can you tell your `ingestr` and `sqlalchemy` versions?

**Comment by IlyaFaer** [comment]
@karakanb, okay, I was finally able to reproduce it. Taking a look...

@rudolfix, I noticed a strange thing. First, I wrote a sample file to reproduce the error just in the `airflow` directory (the one was opened in my IDE). The unexpected thing is that during the script @karakanb provided, the pipeline created to DuckDB databases:
![Untitled](https://github.com/dlt-hub/dlt/assets/26030071/5f63796f-3708-4429-a4b8-189d97381fa5)

Seems to me at some point working directory switch is happening under the hood, and because of that the code can't see the database created earlier.

**Comment by IlyaFaer** [comment]
@karakanb, the problem can be solved by adding a primary key hint into the `incremental`. See:

![Untitled2](https://github.com/dlt-hub/dlt/assets/26030071/ba24ca33-aa7d-4492-950b-a43c93eaa19e)

See for more details:
https://dlthub.com/docs/general-usage/incremental-loading#deduplication-primary_key

**Comment by karakanb** [comment]
isn't this a bug though? the behavior is not like this on different databases, just in duckdb, and I don't want to deduplicate data.

**Comment by IlyaFaer** [comment]
@karakanb, hm-m, I don't know, I have the same in postgres:

![image](https://github.com/dlt-hub/dlt/assets/26030071/2e4c87d5-981d-4382-b2d2-b8efa23b69b5)

Though I'm using the last version of `dlt`.

**Comment by karakanb** [comment]
just to make sure I managed to explain my expectations:
- an incremental load is supposed to load **only** new data
- an incremental load does not have to deduplicate rows, e.g. any SCD2 table
- hence, an incremental load is supposed to not change the destination table if there's no data

these are my assumptions that I base this bug report on. I am sure you guys don't mean to insert new rows when the same pipeline is run twice on the same input data without any data changing, am I right in thinking that?

**Comment by rudolfix** [comment]
@IlyaFaer there are two duckdb databases because one (sample) is a data source from which we load into the pipeline database. so it seems good.

@karakanb `sql_database` does not assume that cursor field is strictly increasing/decreasing on `updated_at`. so it always re-takes the data for recently known `updated_at` and then filters out known records by primary key or by content hash if key is not provided

we also have a small bug that we are fixing but it may come into play when new data is returned unordered which does not happen in your case (no new data, only recently updated_at)

OK I will take a look at this. it looks suspicious

**Comment by rudolfix** [comment]
@karakanb OK thanks to @IlyaFaer observation with primary key, I;ve found the problem. We are, by mistake, generating an empty list as primary key in `sql_table` and this form is used to disable deduplication in `incremental`.

we'll fix it in our code, but you have your copy in ingestr so you can just change this
```python
def get_primary_key(table: Table) -> List[str]:
    """Create primary key or return None if no key defined"""
    primary_key = [c.name for c in table.primary_key]
    return primary_key if len(primary_key) > 0  else None
```

I've found out a few other edge cases for unordered dataset, this does not affect sql table but will be nevertheless fixed here: #1062

**Comment by karakanb** [comment]
hmm, I think this introduces another issue with another usecase:
- there are scenarios where we want to do delete+insert, for instance where the whole of the data for a range might have changed, and we want to completely override the old data.
- in order to achieve this with dlt we use the strategy as `merge` and set `merge_key` to be the `incremental_key`

when I replace the previous `get_primary_key`, this behavior breaks.

here's [the test that fails with this change](https://github.com/bruin-data/ingestr/blob/main/ingestr/main_test.py#L321):
- the source table has two rows: `(1, "val1", "2022-01-01"), (2, "val2", "2022-02-01")`
- I run the command the first time, it copies the data as expected.
- I run the command the second time, this time I expect the row with the date `2022-02-01` to be deleted and reinserted.
- Which means, the first row in the output table would be inserted by the first run, the second row would be inserted by the second run.
- Which means if I get the distinct run IDs in the output table, they should be 2.

The result is 2 for the previous version, but if I apply your change here it becomes 1, the second run touches both of the rows.

am I doing something wrong? is there another way to replicate this behavior?

**Comment by rudolfix** [comment]
This is interesting abuse of the incremental :) cursor column should be used to track changes / new records but indeed you can use it like here.

In the case above row is not re-acquired because it is not changed. Change "val2" -> "val3" and it will get merged.

If you want to offload everything to merge that happens in the load stage just do
`sql_table(...).incremental.primary_key = ()

pls tell me if that worked. I really appreciate your automated tests. This will help us to maintain dlt more stable.
I will also consider to disable deduplication when merge write disposition is detected... I'm just not sure if we are not trying to be too smart here
